# Generated by Django 3.0.5 on 2020-06-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200505_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wall_image',
            field=models.ImageField(default='wood.jpg', upload_to='wall_pic'),
        ),
    ]
