# Generated by Django 2.2.6 on 2019-12-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191211_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='jumbotron',
            field=models.ImageField(default='no image', upload_to='media'),
        ),
    ]
