# Generated by Django 2.2.6 on 2020-03-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200102_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainmentmodel',
            name='source',
        ),
        migrations.AddField(
            model_name='entertainmentmodel',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
