# Generated by Django 2.2.6 on 2020-04-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200324_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsModel',
        ),
    ]
