# Generated by Django 2.2.6 on 2020-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_newsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no image', upload_to='media'),
        ),
    ]
