# Generated by Django 3.0.5 on 2020-04-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='no image', null='True', upload_to='media'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.IntegerField(choices=[(0, 'Na'), (1, 'Entertainment'), (2, 'News'), (3, 'Sports'), (4, 'Tech'), (5, 'Travel')], default=0),
        ),
    ]
