# Generated by Django 3.0.5 on 2020-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200409_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='no image', null='True', upload_to='profile_pics'),
        ),
    ]
