# Generated by Django 3.0.5 on 2020-04-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200410_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='credit',
            field=models.TextField(default='no credits available', null='True'),
            preserve_default='True',
        ),
    ]
