# Generated by Django 3.0.5 on 2020-04-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='credit',
            field=models.CharField(default='no credits available', max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.TextField(max_length=100, null='True'),
        ),
    ]
