# Generated by Django 3.0.5 on 2020-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200414_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.IntegerField(choices=[(1, 'News'), (2, 'Entertainment'), (3, 'Sports'), (4, 'Tech'), (5, 'Travel'), (6, 'Blog')], default=1),
        ),
    ]
