# Generated by Django 3.0.5 on 2020-05-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200502_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hideornot',
        ),
        migrations.CreateModel(
            name='Post_classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('news', '#news'), ('entertainment', '#entertainment'), ('sports', '#sports'), ('tech', '#tech'), ('travel', '#travel')], max_length=20)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='blog.Post')),
            ],
        ),
    ]
