# Generated by Django 3.0.5 on 2020-05-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200522_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classification',
            field=models.CharField(choices=[('news', '#news'), ('entertainment', '#entertainment'), ('sports', '#sports'), ('tech', '#tech'), ('travel', '#travel')], default='news', max_length=20),
        ),
        migrations.DeleteModel(
            name='Post_classification',
        ),
    ]
