# Generated by Django 3.0.5 on 2020-05-23 19:13

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200522_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
