# Generated by Django 3.0.5 on 2020-05-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200527_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classification',
            field=models.CharField(choices=[('news', 'News'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('tech', 'Tech'), ('travel', 'Travel')], default='news', max_length=20),
        ),
        migrations.DeleteModel(
            name='Post_classification',
        ),
    ]
