# Generated by Django 3.0.5 on 2020-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200528_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='credit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
