# Generated by Django 3.0.5 on 2020-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200528_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='credit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
