# Generated by Django 3.0.5 on 2020-06-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200528_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='classification',
            field=models.CharField(choices=[('news', 'News'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('tech', 'Tech'), ('travel', 'Travel')], default=None, max_length=20),
        ),
    ]
