# Generated by Django 3.0.5 on 2020-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20200603_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='classification',
            field=models.CharField(choices=[('none', 'None'), ('news', 'News'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('tech', 'Tech'), ('travel', 'Travel')], default='none', max_length=20),
        ),
    ]
