# Generated by Django 3.0.5 on 2020-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200607_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmodel',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
