# Generated by Django 3.0.5 on 2020-06-16 16:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20200607_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.DeleteModel(
            name='EntertainmentModel',
        ),
    ]
